### ISSUE TITLE
Trying to do simulation of the given input file on LAMMPS

### ISSUE THREAD

**Issue by valipou1** [dwsideriusNIST/LAMMPS_Examples#1]
Hello,

When i try to run this input file on lammps i get this error "Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted."
What does it mean?

**Comment by dwsideriusNIST** [comment]
Can you please point me to the input file that caused this problem? I am happy to try to replicate the error, but I need to know which LAMMPS input file caused the problem.

**Comment by valipou1** [comment]
Hello,

Yes, i'm trying to run this input file  , LJ_initial_cfgs/in.nvt.dens_0.0020 for (SPCE_intial_config) water molecule. I installed open-mpi and use this mpirun -np 4 lmp_mpi -in in.file to run my input file. I would appreciate it if you help me out with the situation.

Sincerely,

Anita

**Comment by dwsideriusNIST** [comment]
Please write our your *exact* execution syntax. I cannot understand what your previous message, as it refers to 1) an LJ initial configuration (which is not a LAMMPS run script) and 2) "SPCE_initial_config" water molecule. I cannot tell if you are attempting to run an LJ sim with that configuration (which needs a separate input file) or an SPC/E sim.

**Comment by valipou1** [comment]
Sorry if i was not clear, I believe i got it figured out, I didn't download the file 'example.sh' and that's why my simulation was not running. I was wondering if is it possible to tell me how did you create the atomic positions of water in the input file. I am trying to do a project which i need to create NaCl +water input file to calculate diffusion, and i have difficulty creating the input file. what software did you use vmd and topotools?

**Comment by dwsideriusNIST** [comment]
I'm glad to hear that you figured out the run script.

Regarding the generation of configurations from LAMMPS, I actually use my own Monte Carlo program to generate configurations. It was a faster setup for me, but it's not very portable to other users.

You may look into other options like:
http://www.ime.unicamp.br/~martinez/packmol/external.shtml
VMD
https://lammps.sandia.gov/prepost.html ("Molecular Builders")

The other route is to just place all the molecules in the box then do an energy minimization, though care must be taken when the molecules have rigid internal bonds. Another option is to place all the molecules in the box (ensuring that there are no overlaps of the LJ spheres) then run MD at high temperature to thermalize the system into a (more) relaxed configuration. There's not a one-size-fits-all approach to generating initial configurations. Sorry.
