### ISSUE TITLE
python2 -> python3

### ISSUE THREAD

**Issue by ianhbell** [dwsideriusNIST/LAMMPS_Examples#3]
In the analysis/block_analysis.py script, the exe is specified as python2, which is end-of-life in three months.  Can you please change it to python3, or better yet, just python?

**Comment by dwsideriusNIST** [comment]
Good catch, I'll update it ASAP.

**Comment by dwsideriusNIST** [comment]
addressed in commit 6e0d4dc1f9348669c3dc0bb44cb14fdd8558887e
